In [111]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("..")
from functools import partial
import torch
from src.frank_wolfe import pseudo_frank_wolfe, term
from src.affine_cond_x import objective_template, objective_gradient, obj_matrix_form, grad_matrix_form, opt_step_len

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [108]:
# Fn check
xs = torch.randn((2,1))
precisions = torch.randn((2,1))
#xs = torch.tensor([[2.0, 3]]).T
#precisions = torch.tensor([[1.0, 2]]).T
sigma_sq_k, sigma_sq_m = 1, 1
full = objective_template(precisions, xs, sigma_sq_k, sigma_sq_m)
mat = obj_matrix_form(precisions, xs, sigma_sq_k, sigma_sq_m)
print(full, mat)

term_1 tensor(-0.0102)
term_2 tensor(-0.0259)
term_3 tensor(1.5776)
term_4 tensor(0.0050)
tensor(1.5366) tensor([[1.5366]])


In [135]:
# Grad check
xs = torch.randn((2,1))
precisions = torch.randn((2,1))
xs = torch.tensor([[2.0, 3]]).T
precisions = torch.tensor([[1.0, 2]]).T
sigma_sq_k, sigma_sq_m = 1, 1
full = objective_gradient(precisions, xs, sigma_sq_k, sigma_sq_m)
mat = grad_matrix_form(precisions, xs, sigma_sq_k, sigma_sq_m)
print(full)
print(mat)

tensor([[8.],
        [9.]])
tensor([[26.],
        [13.]])
tensor([[50.],
        [73.]])


In [105]:
num_samples = xs.size(0)
xs_elem_sq = xs ** 2
first_quadr = xs_elem_sq.repeat((1, num_samples))
second_quadr = xs @ xs.T
quadr_mat = first_quadr - second_quadr
linear = num_samples / sigma_sq_m * xs_elem_sq + num_samples / sigma_sq_k * torch.ones(xs.size())

In [102]:
step_len_selector = partial(opt_step_len, quadr_mat=2*quadr_mat, linear=linear)
pseudo_frank_wolfe(None, )